# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04099c44f3ca98ff4ec20b66340a24181db500aa6d06227183fffdc33160a32353d846553625977dc0e7513a81a8c55ac139d4a8f3c8b0430517aa46450f2a04

test:
  secret_key_base: 2de16f772bab2113f5e34267494dd4b2069d5280d537aee36af9e85226509dac7fde60443f0c1412dbe6fbdbf187512c0322187344371783f034c1b938939f15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
